### PR TITLE
Admin tool test character

### LINKED ISSUE #144: Admin tool test account script [Tool]
Note: this tool is planned to be executed in the **apply_all.bat** script, but will be located in the Tools folder.

Add a Tool script that will contain the following features:
- Create an **Admin tool** type account with the following credentials (user: test, pass: test)
- Add "test" character
- Add bot with the dev_test template to test character
- Set this bot as active
- Set money to 1 Billion nic
- Unlock all extensions

### PR DESCRIPTION
**Pull request by clouths**
Closes: [OP-Project-144](https://github.com/OpenPerpetuum/OP-Project/issues/144)

~~The only thing remaining for this task is to assign the Admin Bot for the active chassis of the test account~~
Done and ready for review.

### CODE REVIEW

**Comment by clouths** [comment]
As pointed out by Marakai, the hardcoded character ID above line 162 (more of less) need to be fixed.
**Edit**: It has been done.

**Comment by clouths** [comment]
Also, Null pointed out that we need to make a lookup for the character before trying to add it.
**Edit**: Done

**Comment by clouths** [comment]
Does this line is required?
[Link to line](https://github.com/OpenPerpetuum/OPDB/blob/e75a597c9f0f5ae5208bde2160d06eaa07b54dfb/Tools/TOOL_test_account.sql#L186)

**Comment by clouths** [comment]
Everything is updated as requested:
- EID generated using the GetRandomEID function for all generated entities
- Cleanup of any existing old test account
- Validation of types when using "if object_id" checks

**Review by MikeJeffers — CHANGES_REQUESTED** [review]
Static review: All new stored procedures should at least go under the `opp` schema so it is easier to sort out what procedures we wrote versus vanilla procedures (that might be used in mysterious ways in the server and do not want to touch/remove)

**Review by MikeJeffers — DISMISSED** [review]
Working for me.  Nice add, test character/account gets things started for locals very nicely.  Great work @clouths

**Comment by clouths** [comment]
The schema of the stored procedures has been changed from 'dbo' to 'opp'

**Review by MikeJeffers — APPROVED** [review]
Good! Thanks for moving them to the other schema =)

**Review by Bler — APPROVED** [review]
Approved

**Pull request merged**
