### PR TITLE
Bug fix on EP bonus item

### PR DESCRIPTION
**Pull request by MikeJeffers**

### CODE REVIEW

**Review by nref-dan — DISMISSED** [review]

**Review by Bler — COMMENTED** [review]
Server is not running on UTC time. Will this create a discrepancy between this time and all other stored times?

**Comment by nref-dan** [comment]
@Bler Yes, but all the dates involved when this is checked are in UTC. This avoids the "Daylight Savings" problem.

**Comment by MikeJeffers** [comment]
@Ketsuekiame Refactor request: UTC -> servertime as all datetimes on server are local datetimes.
We have the fortune of a server located in a TZ that does not observe any weird hour shifts, plus this will make it consistent with all other datetimes (+ other points bler can expand on)

**Comment by MikeJeffers** [comment]
Bugfix consolidated into one script (bler will be re-running all scripts from staging)
Datetime now set to local instead of UTC - as requested

**Comment by MikeJeffers** [comment]
Final Go/No-Go: local datetime - hold the refactor for later

**Review by Bler — APPROVED** [review]
Approved

**Pull request merged**
