### PR TITLE
Create mk2-bugfix

### PR DESCRIPTION
**Pull request by Phantomburn**
bear with me this is my first time.9890+

### CODE REVIEW

**Comment by MikeJeffers** [comment]
There is one very important rule Bler established that should be followed whenever possible:
**No explicit use of indices (ids).**

Try something like:
```
DECLARE @riv_head int;   --This is where we will store a definition of the robot-part
--Now we set the value with a lookup for the definition by the unique-name of the part.
SET @riv_head = (SELECT TOP 1 definition FROM entitydefaults WHERE definitionname='def_riveler_head_mk2');
--Make damn sure that it matches one and only one, if that is the intent

--Now do the same for the field
DECLARE @cpu_field int;
SET @cpu_field = (SELECT TOP 1 id FROM aggregatefields WHERE name='cpu_max');
--Use a Select like this to debug and make sure its getting the value you expect:
--SELECT * FROM aggregatefields WHERE name='cpu_max';

--use the set variables in the update statement below, note you now don't need to know the exact ID numbers (which can be different on different DBs!!!)

UPDATE aggregatevalues SET value=495 where [definition]=@riv_head and [field]=@cpu_field;

--done!
```

**Comment by Phantomburn** [comment]
Yeah makes sense.  Thanks Null.

**Comment by Phantomburn** [comment]
I did the CPU ones, the one I am having trouble with is the hitech numiquol robot bonus.

**Comment by MikeJeffers** [comment]
The railgun cycle updates are fixed up.
File relocated to staging/ and .sql extension added.

The update w/o the definition check _does_ work, but only because of how the bonuses happened to be designed right now.  It will be _safer_ to pick each specific robot-part definition w/ chassis bonus for this update (and future updates).

TODO prev patch cleanup

**Review by Bler — APPROVED** [review]

**Pull request merged**
