### PR TITLE
Pre-Alpha: Content Removal (mk2s, gamma, elites, high-end content...)

### PR DESCRIPTION
**Pull request by MikeJeffers**
@Bler please note how best to handle removals.

Done:
- T2+/T4+
- Elite Heavies
- Lottery tickets (chance of t2+/t4+ and turret modules!)
- EntityDefaults: disable, hidden, non-purchasable
- ItemShop: Deleted
- NPCLoots: Deleted
- PBS - items: Disabled, hidden, non-purchasable
- PBS - research: skill Disabled, Tree 'disabled' (with newtech kernals)
- mk2's : Disabled, hidden, non-purchasable
- Cortexes ---> new issue: make NPC Buy orders @ high nic buys, keep cortexes
- mk2 CT's: Disabled, hidden, non-purchasable (were originally non-purchase)
- mk2 CT's - Artifactloot: Deleted

### CODE REVIEW

**Comment by MikeJeffers** [comment]
hide tech PBS tree with Newtech pointtype

**Comment by MikeJeffers** [comment]
Keep this on hold until after test-weekend.

**Comment by MikeJeffers** [comment]
Closes: https://github.com/OpenPerpetuum/OP-Project/issues/30

**Review by Bler — APPROVED** [review]
looks good selects could be commented out but could be good to see

**Pull request merged**
